eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoints:
    jmx:
      exposure:
        include: "health"
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never

spring:
  main:
    banner-mode: off
  application:
    name: user-service

server:
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true
  port: 8082