eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka
  instance:
    hostname: eureka-discovery-service

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never

server:
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true
  port: 8082

spring:
  main:
    banner-mode: off
  application:
    name: user-service